language: go
sudo: false

go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - tip
env:
  - GIMME_OS=linux
  - GIMME_OS=darwin
  - GIMME_OS=windows
  - GO111MODULE=on

matrix:
  include:
    - go: 1.11
    - go: 1.12
    - go: 1.13
    - go: 1.14
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get -d -v ./...

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go tool vet .
  - GOOS=linux go build -o duckdns-linux
  - GOOS=darwin go build -o duckdns-macos
  - GOOS=windows go build -o duckdns-windowss
  - go build -v ./...
