language: go
sudo: false

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - tip
env:
  - GIMME_OS=linux
  - GIMME_OS=darwin
  - GIMME_OS=windows

matrix:
  include:
    - go: 1.8
    - go: 1.9
    - go: 1.11
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get -d -v ./...

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go tool vet .
  - GOOS=linux go build -o duckdns-linux
  - GOOS=darwin go build -o duckdns-macos
  - go build -v ./...
