language: go
sudo: false

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - tip
env:
  - GIMME_OS=linux
  - GIMME_OS=darwin
  - GIMME_OS=windows

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get -d -v ./...

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go tool vet .
  - go build -v ./...
